# Generated by Django 3.2.2 on 2021-08-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='globaldailyanalysis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='studies_boo_order_b_bd3780_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapter',
            name='studies_cha_book_id_25d1c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='globaldailyanalysis',
            name='studies_glo_user_id_7ed0fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbookmany',
            name='studies_use_user_id_244b7b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userbookmany',
            unique_together=set(),
        ),
    ]
