# Generated by Django 3.2.2 on 2021-08-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userbookmany',
            options={'ordering': ['user', 'order_book']},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='studies_boo_order_b_bd3780_idx',
        ),
        migrations.RemoveIndex(
            model_name='userbookmany',
            name='studies_use_user_id_244b7b_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='order_book',
        ),
        migrations.AddField(
            model_name='userbookmany',
            name='order_book',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='userbookmany',
            index=models.Index(fields=['user', 'order_book'], name='studies_use_user_id_5474be_idx'),
        ),
    ]
