# Generated by Django 3.2.2 on 2021-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='order_book',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order_chapter',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studiesnotes',
            name='order_note',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
