# Generated by Django 3.2.2 on 2021-08-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20210822_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmany',
            name='to_accept',
            field=models.BooleanField(default=False),
        ),
    ]
