# Generated by Django 3.2.2 on 2021-07-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20210720_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmany',
            name='level_chapter',
        ),
    ]
