# Generated by Django 3.2.2 on 2021-08-12 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20210812_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiesnotes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes to studies'},
        ),
        migrations.RemoveIndex(
            model_name='studiesnotes',
            name='studies_stu_chapter_1339a3_idx',
        ),
    ]
