# Generated by Django 3.2.2 on 2021-08-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_userbookmany_to_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
