# Generated by Django 3.2.2 on 2021-08-12 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0003_auto_20210812_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['order_book']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['book', 'order_chapter']},
        ),
        migrations.AlterModelOptions(
            name='globaldailyanalysis',
            options={'ordering': ['user', 'date']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='studiesnotes',
            options={'ordering': ['order_note', 'created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes to studies'},
        ),
        migrations.AlterUniqueTogether(
            name='userbookmany',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['order_book'], name='studies_boo_order_b_bd3780_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'order_chapter'], name='studies_cha_book_id_25d1c1_idx'),
        ),
        migrations.AddIndex(
            model_name='globaldailyanalysis',
            index=models.Index(fields=['user', 'date'], name='studies_glo_user_id_7ed0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='studiesnotes',
            index=models.Index(fields=['chapter', 'order_note'], name='studies_stu_chapter_1339a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userbookmany',
            index=models.Index(fields=['user', 'book'], name='studies_use_user_id_244b7b_idx'),
        ),
    ]
