# Generated by Django 3.2.2 on 2021-08-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210812_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiesnotesprogression',
            options={'ordering': ['user']},
        ),
        migrations.AddIndex(
            model_name='studiesnotesprogression',
            index=models.Index(fields=['user', 'notes'], name='studies_stu_user_id_2108ec_idx'),
        ),
    ]
