# Generated by Django 3.2.2 on 2021-08-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_auto_20210812_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiesnotesprogression',
            options={'ordering': ['user', 'notes']},
        ),
    ]
